# Generated by Django 4.2.3 on 2023-09-16 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter3_project_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 19, 25, 54, 425499, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
