# Generated by Django 4.2.3 on 2024-10-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter3_project_setup', '0002_review_review_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('can_view_review', 'User can review'), ('can_create_review', 'User can create review'), ('can_update_review', 'User can update review'), ('can_partially_update_review', 'User can partially update review'), ('can_delete_review', 'User can delete review')), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='streamplatform',
            options={'permissions': (('can_view_stream_platform', 'User can view stream platform'), ('can_create_stream_platform', 'User can create stream platform'), ('can_update_stream_platform', 'User can update stream platform'), ('can_partially_update_stream_platform', 'User can partially update stream platform'), ('can_delete_stream_platform', 'User can delete stream platform')), 'verbose_name': 'Stream Platform', 'verbose_name_plural': 'Stream Platforms'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'permissions': (('can_view_watchlist', 'User can view watchlist'), ('can_create_watchlist', 'User can create watchlist'), ('can_update_watchlist', 'User can update watchlist'), ('can_partially_update_watchlist', 'User can partially update watchlist'), ('can_delete_watchlist', 'User can delete watchlist')), 'verbose_name': 'Watch List', 'verbose_name_plural': 'Watchlists'},
        ),
    ]
