# Generated by Django 4.2.3 on 2024-10-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter3_project_setup', '0003_alter_review_options_alter_streamplatform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
