# Generated by Django 4.2.3 on 2023-09-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_alter_watchlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='StreamPlatform',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
